version: '3.8'

services:

  libretranslate:
    image: docker.io/libretranslate/libretranslate
    container_name: libretranslate
    build:
      context: .
    command: --load-only tr,en --debug
    ports:
      - "5000:5000"
    restart: unless-stopped

  node:
    image: docker.io/node:latest
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && node server.js"]
    restart: unless-stopped
