version: '3.8'

services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: ["sh", "-c", "ollama pull llama3.2:1b && ollama run llama3.2:1b"]

  libretranslate:
    image: docker.io/libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5000:5000"
    restart: unless-stopped

  node:
    image: docker.io/node:latest
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && node server.js"]
    restart: unless-stopped

volumes:
  ollama:
